Bugfix: fix randomly occur error in BashScriptVariableReader
Sometimes during test the following error occur:
junit.framework.AssertionFailedError: Assertion failed:

assert e.message.startsWith('Script failed with exit code 127. Error output:\n' + 'bash: line 4: missing_dummy_command: command not found')
       | |       |                                                              |
       | |       false                                                          Script failed with exit code 127. Error output:
       | Script failed with exit code 127. Error output:
                       bash: line 4: missing_dummy_command: command not found
       java.lang.RuntimeException: Script failed with exit code 127. Error output:

	at de.dkfz.tbi.otp.utils.BashScriptVariableReaderUnitTests.testExecuteAndGetVariableValues_failingAndSucceedingStatements2(BashScriptVariableReaderUnitTests.groovy:70)

The error looks like that the ouput was not completely read from the process when it access.
Therefore I add code to wait for complete read of the output/error stream.